In [1]:
#Printing stars '*' and 'A' in Right Angle Triangle Shape.

In [3]:
n = int(input("Enter the number of rows: "))
for i in range(n):
    count=0
    for j in range(n-i-1):
        print(" ", end="")
    for j in range(i+1):
        print("*", end="")
        if count<i:
            print("A", end="")
            count=count+1
    print()

Enter the number of rows: 5
    *
   *A*
  *A*A*
 *A*A*A*
*A*A*A*A*


In [4]:
#Printing numbers in Triangle Shape | Column wise | Interview Question

In [6]:
n = int(input("Enter the number of rows: "))
for i in range(n):
    count = i+1
    dec = n-1
    for j in range(i+1):
        print(count, end= " ")
        count = count+dec
        dec = dec-1
    print()

Enter the number of rows: 5
1 
2 6 
3 7 10 
4 8 11 13 
5 9 12 14 15 


In [9]:
n = 5
k = 15
for i in range(n):
    count = k - i
    dec = n-1
    for j in range(i+1):
        print(count, end=" ")
        count = count-dec
        dec = dec - 1
    print()

15 
14 10 
13 9 6 
12 8 5 3 
11 7 4 2 1 


In [2]:
def num(n1):
    if n1==1:
        return 1
    return n1+num(n1-1)
n = int(input("enter the number of rows: "))
k = num(n)
for row in range(n):
    val = k - row
    dec = n-1
    for col in range(row+1):
        print(val, end=" ")
        val = val-dec
        dec = dec - 1
    print()

enter the number of rows: 6
21 
20 15 
19 14 10 
18 13 9 6 
17 12 8 5 3 
16 11 7 4 2 1 


In [3]:
#Matrix class in numpy.

In [4]:
import numpy as np
a = np.matrix("1 2; 2 4")
a

matrix([[1, 2],
        [2, 4]])

In [5]:
b = np.matrix([[10,20], [30,40]])
b

matrix([[10, 20],
        [30, 40]])

In [6]:
a+b

matrix([[11, 22],
        [32, 44]])

In [7]:
a*b

matrix([[ 70, 100],
        [140, 200]])

In [8]:
a.T

matrix([[1, 2],
        [2, 4]])

In [9]:
b.T

matrix([[10, 30],
        [20, 40]])

In [11]:
#Python program for Matrix addition and subtraction.

In [13]:
row = int(input('Enter the row number: '))
col = int(input('Enter the col number: '))

print('Enter the elements for matrix1')
matrix1 = [[int(input()) for i in range(col)] for j in range(row)]
print("matrix1: ")
for i in range(row):
    for j in range(col):
        print(format(matrix1[i][j], "<3"), end="")
    print()
    
print("Enter the elements for matrix2: ")
matrix2 = [[int(input()) for i in range(col)] for j in range(row)]
print("matrix2: ")
for i in range(row):
    for j in range(col):
        print(format(matrix2[i][j], "<3"), end="")
    print()
    
result = [[0 for i in range(col)] for j in range(row)]

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]
    
print("Result is: ")
for i in range(row):
    for j in range(col):
        print(format(result[i][j], "<3"), end="")
    print()

Enter the row number: 2
Enter the col number: 2
Enter the elements for matrix1
5
6
7
8
matrix1: 
5  6  
7  8  
Enter the elements for matrix2: 
10
20
30
40
matrix2: 
10 20 
30 40 
Result is: 
15 26 
37 48 


In [14]:
#Python program for Matrix multiplication.

In [1]:
p = int(input('Enter the row number for matrix1: '))
q = int(input('Enter the col number for matrix2: '))
n = int(input("Enter the column number for matrix1/ row number of matrix2: "))

print('Enter the elements for matrix1')
matrix1 = [[int(input()) for i in range(n)] for j in range(p)]
print("matrix1: ")
for i in range(p):
    for j in range(n):
        print(format(matrix1[i][j], "<5"), end="")
    print()
    
print("Enter the elements for matrix2: ")
matrix2 = [[int(input()) for i in range(q)] for j in range(n)]
print("matrix2: ")
for i in range(n):
    for j in range(q):
        print(format(matrix2[i][j], "<5"), end="")
    print()
    
result = [[0 for i in range(q)] for j in range(p)]

for i in range(p):
    for j in range(q):
        for k in range(n):
            result[i][j] = result[i][j] + matrix1[i][k] * matrix2[k][j]
    
print("Result is: ")
for i in range(p):
    for j in range(q):
        print(format(result[i][j], "<5"), end="")
    print()

Enter the row number for matrix1: 2
Enter the col number for matrix2: 2
Enter the column number for matrix1/ row number of matrix2: 2
Enter the elements for matrix1
11
22
33
44
matrix1: 
11   22   
33   44   
Enter the elements for matrix2: 
55
66
77
88
matrix2: 
55   66   
77   88   
Result is: 
2299 2662 
5203 6050 


In [1]:
#Python program to find Transpose of a Matrix.

In [3]:
p = int(input("Enter the number of rows: "))
q = int(input("Enter the number of columns: "))

print("Enter the elements for matrix1: ")
matrix1 = [[int(input()) for i in range(q)] for j in range(p)]
print("matrix1: ")
for i in range(p):
    for j in range(q):
        print(format(matrix1[i][j], "4"), end="")
    print()

result = [[0 for i in range(p)] for j in range(q)]
for i in range(q):
    for j in range(p):
        result[i][j] = matrix1[j][i]
print("Result: ")

for i in range(q):
    for j in range(p):
        print(format(result[i][j], "<4"), end="")
    print()

Enter the number of rows: 2
Enter the number of columns: 3
Enter the elements for matrix1: 
1
2
3
4
5
6
matrix1: 
   1   2   3
   4   5   6
Result: 
1   4   
2   5   
3   6   


In [1]:
#Create quiz using dictionary | Interview question.

In [5]:
q1 = """Is python case sensitive when dealing with Identifiers?
a. Yes
b. No
c. Machine Dependent.
d. None."""

q2 = """Which of the following is not a keyword?
a. eval
b. assert
c. local
d. pass"""

q3 = """Which one of these is floor division
a. /
b. //
c. %
d. None"""

q4 = """What is the output odf this 3*1**3
a. 27
b. 9
c. 3
d. 1"""

q5 = """"a"+"bc"=??
a. a
b. bc
c. bca
d. abc
"""

questions = {q1:"a", q2:"a", q3:"b", q4:"c", q5:"d"}
name = input("Enter your name: ")
print("Hello", name, "Welcome to the Quiz.")
score = 0
for i in questions:
    print()
    print(i)
    flag1 = input("Do you want to skip this question (yes/no)")
    if flag1 == 'yes':
        continue
    ans = input("Enter your answer (a/b/c/d): ")
    if ans == questions[i]:
        print("Correct answer you got one point.")
        score = score + 1
        print("Current score is", score)
    else:
        print("Wrong answer you lost one point.")
        score = score - 1
        print("Current score is", score)
    flag2 = input("Do you want to skip (yes/no)")
    if flag2 == "yes":
        break
        
print("Final score is: ", score)

Enter your name: Sachin
Hello Sachin Welcome to the Quiz.

Is python case sensitive when dealing with Identifiers?
a. Yes
b. No
c. Machine Dependent.
d. None.
Do you want to skip this question (yes/no)no
Enter your answer (a/b/c/d): a
Correct answer you got one point.
Current score is 1
Do you want to skip (yes/no)no

Which of the following is not a keyword?
a. eval
b. assert
c. local
d. pass
Do you want to skip this question (yes/no)a
Enter your answer (a/b/c/d): a
Correct answer you got one point.
Current score is 2
Do you want to skip (yes/no)no

Which one of these is floor division
a. /
b. //
c. %
d. None
Do you want to skip this question (yes/no)no
Enter your answer (a/b/c/d): b
Correct answer you got one point.
Current score is 3
Do you want to skip (yes/no)no

What is the output odf this 3*1**3
a. 27
b. 9
c. 3
d. 1
Do you want to skip this question (yes/no)no
Enter your answer (a/b/c/d): c
Correct answer you got one point.
Current score is 4
Do you want to skip (yes/no)no

"a"+"

In [6]:
#Inverse of a matrix | Linear Algebra

In [7]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
np.allclose(np.dot(a,b), np.eye(2))

True

In [10]:
np.dot(a,b)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [11]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [12]:
#Power of a matrix | numpy |Linear algebra

In [13]:
import numpy as np
a = np.array([[1,2],[3,4]])
np.linalg.matrix_power(a, 2)

array([[ 7, 10],
       [15, 22]])

In [14]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

In [15]:
np.linalg.matrix_power(a,3)

array([[ 37,  54],
       [ 81, 118]])

In [16]:
np.linalg.matrix_power(a,0)

array([[1, 0],
       [0, 1]])

In [17]:
np.linalg.matrix_power(a, -2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [18]:
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
np.linalg.matrix_power(b,2)

array([[ 5.5 , -2.5 ],
       [-3.75,  1.75]])

In [21]:
#Solve Linear Equation using numpy | Linear Algebra

In [22]:
import numpy as np
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
np.linalg.solve(a,b)

array([2., 3.])

In [23]:
x = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
y = np.array([13,13, 26])
np.linalg.solve(x,y)

array([2., 3., 1.])

In [24]:
#Determinant of a matrix | numpy | Linear Algebra

In [25]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
np.linalg.det(a)

-2.0000000000000004

In [27]:
round(np.linalg.det(a))

-2

In [28]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.linalg.det(b)

0.0

In [30]:
#Python pattern program | Printing numbers in x-shape.

In [34]:
num = input("Enter an odd length number: ")
length = len(num)
for i in range(length):
    for j in range(length):
        if i==j or i+j==length-1:
            print(num, end=" ")
        else:
            print(end=" ")
    print()

Enter an odd length number: 123456
123456     123456 
 123456   123456  
  123456 123456   
  123456 123456   
 123456   123456  
123456     123456 


In [35]:
num = input("Enter an odd length number: ")
length = len(num)
for i in range(length):
    for j in range(length):
        if i==j or i+j==length-1:
            print(num[i], end=" ")
        else:
            print(end=" ")
    print()

Enter an odd length number: 123456
1     1 
 2   2  
  3 3   
  4 4   
 5   5  
6     6 


In [36]:
num = input("Enter an odd length number: ")
length = len(num)
for i in range(length):
    for j in range(length):
        if i==j or i+j==length-1:
            print(num[j], end=" ")
        else:
            print(end=" ")
    print()

Enter an odd length number: 123456
1     6 
 2   5  
  3 4   
  3 4   
 2   5  
1     6 
